# Durations

DECADES = {
    "twenties": "2X",
    "thirties": "3X",
    "forties": "4X",
    "fifties": "5X",
    "sixties": "6X",
    "seventies": "7X",
    "eighties": "8X",
    "nineties": "9X"
  }


TIMEUNIT_MAP = {
    "year": 'YEAR',
    "yr": 'YEAR',
    "month": 'MONTH',
    "mo": 'MONTH',
    "day": 'DAY',
    "hour": 'HOUR',
    "hr": 'HOUR',
    "minute": 'MINUTE',
    "min": 'MINUTE',
    "second": 'SECOND',
    "sec": 'SECOND',
    "millisecond": 'MILLIS',
    "millisec": 'MILLIS',
    "week": 'WEEK',
    "wk": 'WEEK',
    "fortnight": 'FORTNIGHT',
    "quarter": 'QUARTER',
    "century": 'CENTURY',
    "centuries": 'CENTURY',
    "millennia": 'MILLENNIUM',
    "millennium": 'MILLENNIUM',
    "millenia": 'MILLENNIUM',
    "millenium": 'MILLENNIUM'
}

BASIC_NUMBER_MAP = {
    "one": 1,
    "two": 2,
    "three": 3,
    "four": 4,
    "five": 5,
    "six": 6,
    "seven": 7,
    "eight": 8,
    "nine": 9,
    "ten": 10,
    "eleven": 11,
    "twelve": 12,
    "thirteen": 13,
    "fourteen": 14,
    "fifteen": 15,
    "sixteen": 16,
    "seventeen": 17,
    "eighteen": 18,
    "nineteen": 19,
    "twenty": 20,
    "thirty": 30,
    "forty": 40,
    "fifty": 50,
    "sixty": 60,
    "seventy": 70,
    "eighty": 80,
    "ninety": 90,
    "hundred": 100
  }

BASIC_ORDINAL_MAP = {
    "first": 1,
    "second": 2,
    "third": 3,
    "fourth": 4,
    "fifth": 5,
    "sixth": 6,
    "seventh": 7,
    "eighth": 8,
    "ninth": 9,
    "tenth": 10,
    "eleventh": 11,
    "twelfth": 12,
    "thirteenth": 13,
    "fourteenth": 14,
    "fifteenth": 15,
    "sixteenth": 16,
    "seventeenth": 17,
    "eighteenth": 18,
    "nineteenth": 19,
    "twentieth": 20,
    "thirtieth": 30,
    "fortieth": 40,
    "fiftieth": 50,
    "sixtieth": 60,
    "seventieth": 70,
    "eightieth": 80,
    "ninetieth": 90,
    "hundredth": 100
}

